# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, runn tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main



stages:
  - stage: Download_Piper
    jobs:
      - job: downloadPiper
        pool:
          name: Default
          demands:
            - agent.name -equals SAP-AgentPool1
        steps:
        - checkout: none
        - task: Cache@2
          inputs:
            key: piper-cli-official
            path: $(System.DefaultWorkingDirectory)
            cacheHitVar: FOUND_PIPER
          displayName: Cache piper cli binary
        - script: |
              #mkdir -p bin
              curl -L --output $(System.DefaultWorkingDirectory)/piper https://github.com/SAP/jenkins-library/releases/latest/download/piper_master
              chmod +x $(System.DefaultWorkingDirectory)/piper
          condition: ne(variables.FOUND_PIPER, 'true')
          displayName: 'Download Piper'
        - script: $(System.DefaultWorkingDirectory)/piper version
          displayName: 'Piper Version'


####### Piper Libraries #####
  - stage: gCTDS_Deploy
    jobs:
    - job: gctsDeploy
      #variables:
      #- group: development
      pool:
          name: Default
          demands:
            - agent.name -equals SAP-AgentPool1
      steps:
      - task: Cache@2
        inputs:
          key: piper-cli-official
          path: $(System.DefaultWorkingDirectory)
        displayName: gCTS Deploy
      - script: |
          $(System.DefaultWorkingDirectory)/piper gctsDeploy --verbose --host $(ABAP-HOST) --client $(ABAP-CLIENT)  --username $(DEMOCREDS) --password Celebal@123 --repository $(GCTS-REPO)  --remoteRepositoryURL $(REPO-URL) --role TARGET --vSID $(SID)

  - stage: ABAP_Quality_Checks
    jobs:
    - job: executeABAPQualityChecks
      #variables:
      #- group: development
      pool:
          name: Default
          demands:
            - agent.name -equals SAP-AgentPool1
      steps:
      - task: Cache@2
        inputs:
          key: piper-cli-official
          path: $(System.DefaultWorkingDirectory)
        displayName: "ABAP Checks"
      - script: |
          $(System.DefaultWorkingDirectory)/piper gctsExecuteABAPQualityChecks --verbose --client $(ABAP-CLIENT) --host $(ABAP-HOST) --password $(ABAP-PW) --repository $(GCTS-REPO) --username $(ABAP-USER) --remoteRepositoryURL $(REPO-URL) --vSID $(SID) --commit "0d264a0"
