general:
steps:
 gctsDeploy:
  host: "http://S4HANA2021.celebaltech.com:8010"
  client: "200"
  abapCredentialsId: $(DEMOCREDS)
  repository: "adtygpt-adtygpt"
  remoteRepositoryURL: "https://github.com/adtygpt/adtygpt"
  role: "TARGET"
  vSID: "DEV"
  Type: "GITHUB"
  verbose: true
  rollback: false
  
